### ISSUE TITLE
make install报错

### ISSUE THREAD

**Issue by Sherlock-Holo** [VOID001/dev.horo#1]
![](https://img.vim-cn.com/58/543767c428948db2312596bf3eb7b1bd21a8d4.png)

夏娜快解决😋

**Comment by VOID001** [comment]
Do not run with `sudo`
Try 
```

make
make install 
make test

```

**Comment by VOID001** [comment]
Fixed in 0f176bcb26c9317b40eb0a83f16df70d6043c3db
